name: Jekyll Build

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'  # Use your project's Ruby version

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the Jekyll Site
      run: bundle exec jekyll build

    - name: Deploy
      run: echo "Deploy step goes here"
